<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ricardo.20200819082445.1"><vh>@auto source/sistemas-de-control-de-versiones-i.md</vh></v>
<v t="ricardo.20200819082445.2"><vh>@auto source/sistemas-de-control-de-versiones-ii.md</vh></v>
<v t="ricardo.20200819082445.3"><vh>@auto source/introduccion-a-la-tecnologia-web.md</vh></v>
<v t="ricardo.20200819082445.4"><vh>@auto source/conceptos-basicos-de-php-i.md</vh></v>
<v t="ricardo.20200819082445.5"><vh>@auto source/conceptos-basicos-de-php-ii.md</vh></v>
<v t="ricardo.20200819082445.6"><vh>@auto source/desarrollo-de-aplicaciones-con-php-i.md</vh></v>
<v t="ricardo.20200819082445.7"><vh>@auto source/persistencia-de-datos-con-php.md</vh></v>
<v t="ricardo.20200819082445.8"><vh>@auto source/desarrollo-de-aplicaciones-con-php-ii.md</vh></v>
<v t="ricardo.20200819082445.9"><vh>@auto source/programacion-avanzada-en-php.md</vh></v>
<v t="ricardo.20200819082445.10"><vh>@auto source/interoperabilidad.md</vh></v>
<v t="ricardo.20200819082445.11"><vh>@auto source/introduccion-a-yii-2.md</vh></v>
<v t="ricardo.20200819082445.12"><vh>@auto source/estructura-de-una-aplicacion-yii-2.md</vh></v>
<v t="ricardo.20200819082445.13"><vh>@auto source/gestion-de-peticiones-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.14"><vh>@auto source/acceso-a-bases-de-datos-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.15"><vh>@auto source/creacion-y-validacion-de-formularios-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.16"><vh>@auto source/visualizacion-de-datos-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.17"><vh>@auto source/seguridad-y-cacheado-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.18"><vh>@auto source/caracteristicas-adicionales-de-yii-2.md</vh></v>
<v t="ricardo.20200819082445.19"><vh>@auto source/calidad.md</vh></v>
<v t="ricardo.20200819082445.20"><vh>@auto source/computacion-en-la-nube.md</vh></v>
<v t="ricardo.20200819082445.21"><vh>@auto source/servicios-web-con-rest-en-yii-2.md</vh></v>
<v t="ricardo.20200819082445.22"><vh>@auto source/contenedores.md</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
