exclude:
    - vendor
    - slides/reveal.js/plugin/markdown/example.md
    - slides/reveal.js/plugin/reveal.js-menu/README.md
    - slides/reveal.js/plugin/reveal.js-quiz/README.md
    - slides/reveal.js/test/simple.md
    - slides/reveal.js/css/theme/README.md
# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack
lang: es-es
timezone: Europe/Madrid
accent_color: '#8f5536'
accent_image: assets/img/sidebar-bg.jpg
color: '#8f5536'
logo: assets/logo.png
url: https://dwese.iesdonana.org
baseurl: ''
author:
  name: Ricardo Pérez López
  email: ricardo@iesdonana.org
  social:
    github: ricpelo
    youtube: UCNEGJcMlhkESHHhGCixbaxg
tagline: Desarrollo web en entorno servidor
defaults:
  - scope:
      path: informacion-general.md
    values:
      menu: true
      order: 1
  - scope:
      path: objetivos-generales.md
    values:
      menu: true
      order: 2
  - scope:
      path: resultados-aprendizaje-criterios-evaluacion.md
    values:
      menu: true
      order: 3
  - scope:
      path: diapositivas.md
    values:
      menu: true
      order: 4
