exclude: ['slides/reveal.js/*.md', 'slides/reveal.js/*.html']
# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack@gem-7.5.1
lang: es-es
accent_color: '#8f5536'
url: https://dwese.iesdonana.org
baseurl: ''
author:
  name: Ricardo Pérez López
  email: ricardo@iesdonana.org
  twitter: ricpelo
  github: ricpelo
tagline: Desarrollo web en entorno servidor
data:
  strings:
    pages: 'Páginas'
