exclude: ['slides/reveal.js/*.md', 'slides/reveal.js/*.html', 'vendor']
# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack
lang: es-es
accent_color: '#8f5536'
accent_image: assets/img/sidebar-bg.jpg
color: '#8f5536'
url: https://dwese.iesdonana.org
baseurl: ''
author:
  name: Ricardo Pérez López
  email: ricardo@iesdonana.org
  social:
    github: ricpelo
    youtube: https://www.youtube.com/channel/UCNEGJcMlhkESHHhGCixbaxg
tagline: Desarrollo web en entorno servidor
data:
  strings:
    pages: 'Páginas'
defaults:
  - scope:
      path: informacion-general.md
    values:
      menu: true
      order: 1
  - scope:
      path: objetivos-generales.md
    values:
      menu: true
      order: 2
  - scope:
      path: resultados-aprendizaje-criterios-evaluacion.md
    values:
      menu: true
      order: 3
  - scope:
      path: diapositivas.md
    values:
      menu: true
      order: 4
